#source 'https://cdn.cocoapods.org/'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/jiangyanshuang/YSPodSpec.git'

use_frameworks!

platform :ios, '10.0'

target 'YSTools_Example' do
  pod 'YSTools'#, :path => '../'

  target 'YSTools_Tests' do
    inherit! :search_paths

#    pod 'FBSnapshotTestCase'
  end
end
